language: python
dist: focal
python:
 - "3.8"
 - "3.9"
 - "3.10"
install:
  - pip install -U pytest pytest-console-scripts pytest-check
  - python3 setup.py install
script:
  - PYTHONPATH=src python3 -m pytest tests
